### ISSUE TITLE
ClientInfo.cs missing 

### ISSUE THREAD

**Issue by Jonesie** [conwid/GistManager#1]
Hi
I was going to try improve your extension for the VS dark theme but there is a file missing from the source :(

**Comment by conwid** [comment]
Great idea, looking forward to that capability!
The missing file is intentional. I have updated the Contributing section of the Readme file with the relevant information.

**Comment by Jonesie** [comment]
Ive never created a Github app.  Could you tell me what the values are for permissions, callback url etc?

Thanks

**Comment by conwid** [comment]
I'm not really sure about the permissions, because as far as I can tell, there's no way to edit them after the application is created. I think you need to set all the gist related ones (editing, deleting etc).
For the callback url, you have to first go to the [Constants.cs file](https://github.com/conwid/GistManager/blob/master/GistManager/Constants.cs), and here basically you have to set any valid url value for the RedirectUri (it doesn't need to be an existing page, but the format must be valid) and then specify the same value for the callback url when creating the app.
